language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
- 7.3
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.9.3.10
    env: MAGENTO_VERSION=ce-1.9.2.4
    env: MAGENTO_VERSION=ce-1.9.1.1
  - php: 7.1
    env: MAGENTO_VERSION=ce-1.9.3.10
    env: MAGENTO_VERSION=ce-1.9.2.4
    env: MAGENTO_VERSION=ce-1.9.1.1
  - php: 7.2
    env: MAGENTO_VERSION=ce-1.9.3.10
    env: MAGENTO_VERSION=ce-1.9.2.4
    env: MAGENTO_VERSION=ce-1.9.1.1
  - php: 7.3
    env: MAGENTO_VERSION=ce-1.9.3.10
    env: MAGENTO_VERSION=ce-1.9.2.4
    env: MAGENTO_VERSION=ce-1.9.1.1
env:
  global:
  - APPNAME=Ffuenf_DeleteOrder
  - secure: gFyjyFP64t7cK+QVZ+UKH3td7OjXGQZ2aDmNWT5LDuIZx9fQvrwXx6yUDakXoqOiANDklgzH/Y3djYakb22miBwLwY/I4vCfcEKgNCa2NWrWHJKRPKv2UTPxIrmsRg3ZKSDoHs+Y02ryqETOw6FEi4eDeTyEJmixA9jYoAr/Ch8=
  - secure: VsFR1wQV/aV8fCLMgXgBBjsFMFN11ZJgykXCnUJQGDEx+BLyYVtyXkTH6hm7PIOvTdO3Gz0JdzWNCYT9YRB06/H7lvp07g/f/qyPP+EJAUuOhTpYszoeIpQg2oNt7sFNkmI1b/XYCXzSATF+tZwgg8M8RS2lKQdw4OUKO/BI4X8=
  - secure: CeVPTW1p3PfbnrBncRkshYcAtbNxdscQ07r1UhXe7/AFMsophqG3/lgpA9scrMM+LRPiPUanxSa67SEQ5sGsg5i3BewJ63ClsgIiizvOqYY7qYpdjfLs18AH7+DelpfDWXnVAoUis8RQG1F1EVjqQJcJWme86q9nb8ss9ZAiOy4=
  matrix:
  - MAGENTO_VERSION=ce-1.9.4.0
  - MAGENTO_VERSION=ce-1.9.3.10
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: RsY+ADT34SQEkuHbKJ8mK8Ev+Zyd7oPUCEkedXTkueVfp6PMNFhRGptFx5hqDR3mVY9XPmlzkODg6VWqTW+cdV86ACJ9MMXQ86d6s1FqsF8g2/t0Err8CAmd1B5iFo+YlU5QCPNMGU4sAHluugD7Y/ErMXJz+Ul7rdv7AOXvIK0=
notifications:
  slack:
    secure: dGa0DQXE7JxuMoido36l1JVS9UCtQ1uOyv8hfJjgXcxVdgfp0GIJ7r6bmL7M0Sce/lHgkpEUJflUgSxWqtlYBipBy0X94S9kveu/pZ3RhT1ZLPw6Rk2IgxyU0SxS4u0PIGSsuWZNJ/tgINwxYqyvhcNjhF2uNxlXwA7zX8FugZo=
