language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_DeleteOrder
  - secure: yaImvLww1FGWtZfuFqyD6MsWzKZdx68Mpy/fon4lchd2ld32HGOh5mG9jdtkZ9xM65n8UGJANAPcGUcI8nceFlIlGTEF61d/StS3XciNYzCOBxxGWJmvG+CcAdVp0zIIpydN5M2bsFTBhdWWs+X+KBxSuyY1jJlHYSt5+FcUPxo=
  - secure: W8fStL3whAoKZhqjKarz9TPAI17gctQofRjuNAmmzGG1UOR6zFISwKk47F0aQnI2F1V+Ny1poMdEAEBIJwojWGLfa1S4jgoS5uyANBKEjrGV6jXrLitmQkXqE3167i8V2PkBPAf3UkXPg/qvQPWfoGYbhH3t0uYi87ALodvCxCE=
  - secure: WFrNOBRE7dFp7P3xQocED6Z5ES8D7L3Rk81UskSx+pTGoL9ashm3hhLuobjy3Kk4AK4+X0Q3Eu5rPdcKULC4MQ67ASSJ2nBuDoQunnULYoc4h0twom3AhGNnZGuZIp4U8Sn7HarKLqEec0PeiuGOyYdPiAJ5lPEERGyt6b1OPqU=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.10
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: guC3Wxvk7chTmoGpjD7gv12/2kupn9Im16i48Ifh0l46d/Er47s6/B4P6fZnes/l0k0sgj6ijZTf3CXfhai+gLeOIuQU8kCLtFsTotquYwqZ3Cgc5CF6q4n12Lmxt8xlolA0akbN9S99TmWSPTouPY18plW3vajHLuqucVRYrYo=
notifications:
  slack:
    secure: oLCEicC5sRKZMTjC9ZjE7yQDVTpLmNDoG2c39uRkucB76dNB32yPoQYnW+4Yaa89OiYinfpebKdI6EMjMpLcyKwBhaHlsRJaJu5QKMoyGjifWNdAngfnRnC7LJAsUhe/J8OGCDXI0EJdUkRQQWA/MlB5y6hHXO1zsn0KcrqEf4Y=
