language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_DeleteOrder
  - secure: A4ifSdivBn5K8ekZXmvyDtmN4/39+wKNOljsOkyxTLKgDjsKkC5u8wx43MQBDv0YRQsA7i3QVLo6a7QVfww8uRy1wmz+Pg9DDNBvZJXBNVU0hT11wo/thQhQKanra1arSm98LWl3rW7ICenTe5BgnzPIYqmzZAFu3LyJtk4h7IU=
  - secure: Dqhyhm7Y26NCh8BCgwNoS2ubfI75koyrKragGSkQNcAcfuKnm4k5LVgT3nIbeUp5jVqmkfuoCBTzicHBFuf8Mb4PdzU1ppqH60qnqCMzi0jo0FodaMTzUkyPcGtzTE8E3TNfMkRTfVn2pVB7K66Y7NuWxSUgGok91jcjq1X5ofA=
  - secure: 4iYD4/H0I6SxRKDEGHjww8zHE7CwEuGEhJpHpFLXS+kDBtjob4ZaJ6BLbvoKibOnt0zQ29J7tBNaM4DWE7oTjVjvhXVfccgF7kElkjCBLuwJ3Pkc8PpmZTNB42b9be7K2yUzheGTfkFuh4QDEacMCR68fJmlCnMkndjx2K1r3Cw=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.10
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: 1AOSWx8P6ateDbBBOqj6QsiOfy8yu+rGCHjtSmadtuH5bBEs0YVyZGS6dant2PL3ukmnDwxoC22DVyVrlYQi/LiXvhYrLsqRZSpvdEIs2vgEYPIA7rS7PmxhfFuP2z3RVqi4/TO0cF+uxneGDqcc8NckrNaajftVMzYlg6vjfh0=
notifications:
  slack:
    secure: Of0cTeBFOr82MdUapqa51gkYZg9uuoBH+L66FOF1damyDIvRGSf3UxozNEhNqG4JqElSJUhZNLoLBKfG7nB690XVSrGTvBlXw8IPyA+wvQ9EUSConsd8CNAUPvLKRHP7+1nYJdaEim+I+3Z4SgGwLvqRXWJbvFH1JmcDxI9kylI=
