language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
  - php: 7.1
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_DeleteOrder
  - secure: ZI79v6djPdLLW4NoneXFRONInvtiX4bLuygqD0V67u5kGzPbIJsRVBYUnqd6wguVHxy/UBxlqHFj02aqJDPqh4a8qu0zjQaoBhugir2iHA4hUDy808F9EqUWzf7f0APB+V085kqlbPOuX7FQqoTt54maeYdgHlri/+E5ThFjqmo=
  - secure: BQeCNaUbyfP5tiWir0eDC0kq9cdcYC7oDEcGlPoSJ6WxoeOmEzlPD2CIwycDlXixwXtCRmD10iJKSrEYB+WWtCg24JM3bl6KvDZKaKB7AjTU5BYmws2rDY2q0ohNvv3+Qhf23Bo8tasowfyGK8hQxW3jjzDeZ6/XFp7beElMqs0=
  - secure: TVvagZaT/0+RF86i5ZgkAwzMjDP3nU/RDEG5suqt8NkLsEMhIu2CiaxbBq1RWQRUaUI2RsVB2WI79rjxjBJtbUAlU+w+YTriT4Ps1KufyfmQLqKUI4FOJ0xYl0VG7+IEpbJh1SKO2fH2njZYlUPkjwwjBCgTMs5kwIJjYqTKsfc=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.7
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/dev/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/dev/script.sh |
  bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: 0xfpzy1IeZC0tWyemBWrNvH74loVx102CJG7VQzCxdeeYeifDbBfNqROq/2V1OOdmMBM2HnOrR/xQkMmjicVsW7rWjXjjvHOn3XkKJPVK2nArKUF8i8+MNGf4FmiTvxhfnS17O2rXGrUmOM9JIBoV0eMxHgqa0G8jSqTE1qfbMQ=
notifications:
  slack:
    secure: wUeaYdxW/A0OFi35CNoemXvC4cOc6GW1E8g7HZZMq/ETYCifNooc0ZKRaBFPX8Pw3UBgxEjGV72U/Gg02G23Cv4w/Cy8MCi37fSNbV6tgES0HMaqTqSX0FOWyfpDqavpugu5FvdTTkdtOBVrpejo9249evEFRMYWBMIAL/qyLCQ=
